using System.IO;
/* Generated by MyraPad at 15/05/2022 12:02:59 */
using FontStashSharp;
using Myra.Graphics2D;
using Myra.Graphics2D.UI;

namespace PingPong
{
	public class LanUI : Grid
	{
		public TextBox IpInput;
		public ImageTextButton initLanButton;
        public ImageTextButton backButton;
		
		public LanUI()
		{
			BuildUI();
		}

		private void BuildUI()
		{
			byte[] ttfData = File.ReadAllBytes("./Data/fonts/buttons.otf");
            FontSystemSettings fontSet = new FontSystemSettings{Effect = FontSystemEffect.Stroked, EffectAmount = 2};
            FontSystem font = new FontSystem(fontSet);
			font.CharacterSpacing = 5;
            font.AddFont(ttfData);
			
			IpInput = new TextBox();
			IpInput.HintText = "Lan IP - If empty set server";
			IpInput.Height = 40;
            IpInput.Width = 500;
			IpInput.TextVerticalAlignment = VerticalAlignment.Center;
			IpInput.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			IpInput.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			IpInput.Margin = new Thickness(0, 0, 0, 250);
			IpInput.Id = "LanText";
			IpInput.Font = font.GetFont(30);

			ttfData = File.ReadAllBytes("./Data/fonts/buttons.otf");
            fontSet = new FontSystemSettings{Effect = FontSystemEffect.Stroked, EffectAmount = 2};
            font = new FontSystem(fontSet);
            font.AddFont(ttfData);

			initLanButton = UI.DefaultTextButton("Lan Game", font);
			initLanButton.Margin = new Thickness(0, 200, 0, 0);
			
            backButton = UI.DefaultTextButton("Back", font);
			backButton.Margin = new Thickness(0, 0, 0, 0);

			Widgets.Add(IpInput);
			Widgets.Add(initLanButton);
            Widgets.Add(backButton);
		}
	}
}
