using System.IO;
/* Generated by MyraPad at 15/05/2022 12:02:59 */
using FontStashSharp;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
//using System.Drawing;
using System.Numerics;
#endif


namespace PingPong
{
	public class LanUI : Grid
	{
		public LanUI()
		{
			BuildUI();
		}

		private void BuildUI()
		{
			byte[] ttfData = File.ReadAllBytes("./Data/fonts/buttons.ttf");
            FontSystemSettings fontSet = new FontSystemSettings{Effect = FontSystemEffect.Stroked, EffectAmount = 2};
            FontSystem font = new FontSystem(fontSet);
			font.CharacterSpacing = 5;
            font.AddFont(ttfData);
			
			IpText = new TextBox();
			IpText.HintText = "Lan IP - If empty it will be set to server";
			IpText.Height = 40;
            IpText.Width = 500;
			IpText.TextVerticalAlignment = VerticalAlignment.Center;
			IpText.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			IpText.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			IpText.Margin = new Thickness(0, 0, 0, 250);
			IpText.Id = "LanText";
			IpText.Font = font.GetFont(30);

			ttfData = File.ReadAllBytes("./Data/fonts/buttons.ttf");
            fontSet = new FontSystemSettings{Effect = FontSystemEffect.Stroked, EffectAmount = 2};
            font = new FontSystem(fontSet);
            font.AddFont(ttfData);

			LanGameBtn = UI.DefaultTextButton("Lan Game", font);
			LanGameBtn.Margin = new Thickness(0, 200, 0, 0);
			
            BackBtn = UI.DefaultTextButton("Back", font);
			BackBtn.Margin = new Thickness(0, 0, 0, 0);

			Widgets.Add(IpText);
			Widgets.Add(LanGameBtn);
            Widgets.Add(BackBtn);
		}

		
		public TextBox IpText;
		public ImageTextButton LanGameBtn;
        public ImageTextButton BackBtn;
	}
}
