using System.Collections.Generic;
/* Generated by MyraPad at 13/05/2022 13:27:11 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using Myra.Graphics2D.UI.Styles;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace PingPong
{
	partial class LanUI: Grid
	{
		private void BuildUI()
		{
			LanText = new TextBox();
			LanText.HintText = "Lan IP - If empty it will be set to server";
            LanText.MinWidth = 200;
			LanText.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			LanText.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			LanText.Margin = new Thickness(0, 0, 0, 150);
			LanText.Id = "LanText";

			LanGame = new TextButton();
			LanGame.Text = "Lan Game";
			LanGame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			LanGame.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			LanGame.Id = "LanGame";
			
            Back = new TextButton();
			Back.Text = "Back";
			Back.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Back.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
            Back.Margin = new Thickness(0, 0, 0, 100);
			Back.Id = "Back";
			

			Widgets.Add(LanText);
			Widgets.Add(LanGame);
            Widgets.Add(Back);
		}

		
		public TextBox LanText;
		public TextButton LanGame;
        public TextButton Back;
	}
}
