/* Generated by MyraPad at 13/05/2022 13:27:11 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace PingPong
{
	partial class TitleUI: Grid
	{
		private void BuildUI()
		{
			Normal = new TextButton();
			Normal.Text = "Main Game";
			Normal.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Normal.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Normal.Margin = new Thickness(0, 0, 0, 150);
			Normal.Id = "Normal";

			Lan = new TextButton();
			Lan.Text = "Lan Game";
			Lan.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Lan.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Lan.Id = "Lan";
			
			Widgets.Add(Normal);
			Widgets.Add(Lan);
		}

		
		public TextButton Normal;
		public TextButton Lan;
	}
}
