using System.IO;
/* Generated by MyraPad at 15/05/2022 12:02:59 */
using FontStashSharp;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
//using System.Drawing;
using System.Numerics;
#endif

namespace PingPong
{
	public class TitleUI: Grid
	{
		public TitleUI()
		{
			BuildUI();

		}
		private void BuildUI()
		{
			
			byte[] ttfData = File.ReadAllBytes("./Data/fonts/title.ttf");
            FontSystemSettings fontSet = new FontSystemSettings{Effect = FontSystemEffect.Stroked, EffectAmount = 2};
            FontSystem font = new FontSystem(fontSet);
            font.AddFont(ttfData);

			title = new TextBox();
			title.Text = "PING PONG";
			title.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			title.Margin = new Thickness(0, 100, 0, 0);
			title.Background = new SolidBrush("#00000000");
			title.Id = "title";
			title.Font = font.GetFont(128);
			title.Readonly = true;
			title.AcceptsKeyboardFocus = false;
			title.Selection = new SolidBrush("#00000000");

			ttfData = File.ReadAllBytes("./Data/fonts/buttons.ttf");
            fontSet = new FontSystemSettings{Effect = FontSystemEffect.Stroked, EffectAmount = 2};
            font = new FontSystem(fontSet);
            font.AddFont(ttfData);

			NormalGameBtn = UI.DefaultTextButton("Normal Game", font);
			NormalGameBtn.Margin = new Thickness(0, 120, 0, 0);

            LanUIBtn = UI.DefaultTextButton("Lan Game", font);
			LanUIBtn.Margin = new Thickness(0, 300, 0, 0);

			
			Widgets.Add(title);
			Widgets.Add(NormalGameBtn);
			Widgets.Add(LanUIBtn);
		}

		
		public TextBox title;
		public ImageTextButton LanUIBtn;
		public ImageTextButton NormalGameBtn;
	}
}
